module.exports = {
"atmosphere": ["The small cafe had a relaxed atmosphere that made customers want to stay.", "这家小咖啡馆气氛轻松，让顾客都想多坐一会儿。"],
"oxygen": ["Divers must carry tanks of oxygen when they explore deep water.", "潜水员探索深水时必须携带氧气瓶。"],
"oxide": ["Rust is an oxide that forms when iron is exposed to damp air.", "铁锈是铁暴露在潮湿空气中形成的氧化物。"],
"carbon dioxide": ["Plants absorb carbon dioxide and release oxygen during the day.", "植物在白天吸收二氧化碳并释放氧气。"],
"hydrogen": ["Hydrogen is the lightest element and burns with a nearly invisible flame.", "氢是最轻的元素，燃烧时火焰几乎看不见。"],
"core": ["The core of the problem lies in how the budget was planned.", "问题的核心在于预算当初是怎么规划的。"],
"crust": ["The crust of the bread was golden and pleasantly crisp.", "面包的外皮金黄酥脆，口感很好。"],
"mantle": ["A thick layer of rock called the mantle lies beneath the crust.", "地壳之下是厚厚的一层岩石，称为地幔。"],
"take up": ["Learning to play the violin takes up most of her free time.", "学小提琴占去了她大部分的业余时间。"],
"longitude": ["Sailors once used the stars to work out their longitude at sea.", "水手过去靠星辰来计算自己在海上的经度。"],
"latitude": ["Cities near the same latitude usually share a similar climate.", "纬度相近的城市通常气候也相似。"],
"horizon": ["A thin line of ships appeared on the horizon just before sunset.", "就在日落前，一条细细的船影出现在地平线上。"],
"altitude": ["At this altitude the air is thin and breathing becomes difficult.", "在这样的海拔上空气稀薄，呼吸会变得困难。"],
"disaster": ["The flood was the worst natural disaster the region had seen in decades.", "这场洪水是该地区几十年来最严重的自然灾害。"],
"mishap": ["Apart from a minor mishap with the luggage, the trip went smoothly.", "除了行李出了点小意外，这趟旅行很顺利。"],
"catastrophic": ["Cutting the budget now would have catastrophic effects on research.", "现在削减预算会对研究造成灾难性的影响。"],
"calamity": ["The village never fully recovered from the calamity of that winter.", "那个村子始终没能从那场冬季灾难中完全恢复。"],
"endanger": ["Illegal hunting continues to endanger several rare species.", "非法捕猎仍在危及若干稀有物种。"],
"jeopardise": ["One careless mistake could jeopardise the whole project.", "一个粗心的错误就可能危及整个项目。"],
"destructive": ["The storm was far more destructive than anyone had predicted.", "这场风暴的破坏力远超所有人的预料。"],
"greenhouse": ["Tomatoes grow well in a greenhouse even in early spring.", "即使在早春，番茄在温室里也长得很好。"],
"phenomenon": ["Scientists are still trying to explain this unusual phenomenon.", "科学家仍在试图解释这一异常现象。"],
"pebble": ["She picked up a smooth pebble and skipped it across the lake.", "她捡起一块光滑的鹅卵石，在湖面上打起了水漂。"],
"magnet": ["The child was instantly drawn to the toy shop like a magnet.", "孩子像被磁铁吸引一样立刻被玩具店吸引过去。"],
"ore": ["The mine produces ore that is rich in copper.", "这座矿出产的矿石含铜量很高。"],
"mineral": ["This region is famous for its mineral springs and clean air.", "这个地区以矿泉和清新的空气闻名。"],
"marble": ["The hotel lobby had a marble floor that shone under the lights.", "酒店大堂的大理石地面在灯光下闪闪发亮。"],
"quartz": ["A quartz crystal can keep time with remarkable accuracy.", "石英晶体可以极其精确地计时。"],
"granite": ["The old church was built entirely of grey granite.", "这座老教堂完全是用灰色花岗岩建成的。"],
"gust": ["A sudden gust of wind blew the papers off the desk.", "一阵突如其来的风把桌上的文件吹落一地。"],
"breeze": ["A cool breeze from the sea made the hot afternoon bearable.", "海上吹来的凉风让炎热的午后变得可以忍受。"],
"monsoon": ["Farmers here depend on the monsoon to water their fields.", "这里的农民靠季风来浇灌田地。"],
"gale": ["The gale was so strong that the ferry service was cancelled.", "大风太猛，渡轮服务被迫取消。"],
"hurricane": ["Residents were advised to leave the coast before the hurricane arrived.", "居民被建议在飓风到来前撤离海岸。"],
"tornado": ["The tornado destroyed several farms in less than ten minutes.", "龙卷风在不到十分钟内摧毁了好几个农场。"],
"typhoon": ["Schools were closed for two days because of the typhoon.", "因为台风，学校停课两天。"],
"volcano": ["The volcano has been quiet for over a century.", "这座火山已经沉寂了一个多世纪。"],
"erupt": ["Scientists warn that the mountain could erupt at any time.", "科学家警告这座山随时可能喷发。"],
"magma": ["Magma slowly rises towards the surface beneath the island.", "岩浆在岛屿下方缓慢地向地表上升。"],
"tsunami": ["The tsunami swept away dozens of houses along the shore.", "海啸冲走了沿岸几十座房屋。"],
"thermodynamic": ["The engineer explained the thermodynamic process behind the engine.", "工程师解释了这台发动机背后的热力学过程。"],
"smog": ["Thick smog covered the city and schools advised children to stay indoors.", "浓重的烟雾笼罩城市，学校建议孩子待在室内。"],
"fume": ["Toxic fumes from the factory drifted over the nearby village.", "工厂排出的有毒烟雾飘向附近的村庄。"],
"mist": ["Early morning mist covered the valley like a soft blanket.", "清晨的薄雾像柔软的毯子一样覆盖着山谷。"],
"drought": ["The long drought left the fields dry and cracked.", "长期干旱让田地干裂。"],
"flooding": ["Heavy rain caused serious flooding in the lower part of town.", "大雨造成城镇低洼地区严重内涝。"],
"torrent": ["After the storm a torrent of brown water rushed down the hill.", "暴风雨过后，一股棕色的激流从山上冲下来。"],
"earthquake": ["The earthquake struck without warning in the middle of the night.", "地震在半夜毫无预兆地发生。"],
"seismic": ["The country installed new seismic equipment to monitor the fault line.", "该国安装了新的地震设备来监测断层线。"],
"avalanche": ["Two climbers were buried by an avalanche near the summit.", "两名登山者在峰顶附近被雪崩掩埋。"],
"terrain": ["The rescue team had to cross extremely rough terrain.", "救援队不得不穿越极为崎岖的地形。"],
"landscape": ["The winter landscape was completely silent and covered in white.", "冬日的景色一片寂静，覆盖着白雪。"],
"continent": ["Africa is the second largest continent in the world.", "非洲是世界第二大洲。"],
"cliff": ["The path along the cliff offered spectacular views of the sea.", "沿悬崖的小路能看到壮丽的海景。"],
"glacier": ["The glacier has retreated several kilometres in recent years.", "近年来这座冰川退缩了好几公里。"],
"swamp": ["The hikers had to find a way around the swamp.", "徒步者不得不绕开那片沼泽。"],
"delta": ["Fertile soil collects where the river forms a wide delta.", "河流形成宽阔三角洲的地方会淤积出肥沃的土壤。"],
"plain": ["Cattle grazed peacefully on the wide grassy plain.", "牛群在广阔的青草地上安静地吃草。"],
"plateau": ["After weeks of climbing they finally reached the plateau.", "爬了几周后，他们终于登上了高原。"],
"oasis": ["The travellers were relieved to find an oasis in the desert.", "旅行者在沙漠中找到绿洲，松了一口气。"],
"globe": ["The teacher spun the globe to show us where the country was.", "老师转动地球仪给我们指出那个国家的位置。"],
"hemisphere": ["Summer in the southern hemisphere begins in December.", "南半球的夏天从十二月开始。"],
"equator": ["Countries near the equator have little difference between seasons.", "赤道附近的国家四季差别很小。"],
"arctic": ["Few animals can survive the harsh arctic winter.", "能在严酷的北极冬季存活的动物很少。"],
"Antarctic": ["The Antarctic is the coldest and windiest place on Earth.", "南极是地球上最冷、风最大的地方。"],
"pole": ["Expeditions to the pole were once incredibly dangerous.", "过去前往极点的探险极其危险。"],
"polar": ["Polar bears depend on sea ice to hunt seals.", "北极熊依靠海冰来捕猎海豹。"],
"axis": ["The Earth rotates on its axis once every twenty-four hours.", "地球每二十四小时绕地轴自转一圈。"],
"deteriorate": ["His health began to deteriorate rapidly last winter.", "去年冬天他的健康状况开始迅速恶化。"],
"aggravate": ["Shouting at him will only aggravate the situation.", "对他大喊只会让情况更糟。"],
"degrade": ["Plastic waste takes centuries to degrade in the ocean.", "塑料垃圾在海洋中需要几个世纪才能降解。"],
"erode": ["Waves gradually erode the soft rock along the coast.", "海浪逐渐侵蚀海岸上的软岩。"],
"pacific": ["The pacific coast is known for its mild winters.", "太平洋沿岸以冬季温和著称。"],
"ocean": ["The ocean covers more than seventy percent of the planet.", "海洋覆盖了地球七成以上的面积。"],
"marine": ["Marine life in this bay is protected by strict local laws.", "这个海湾的海洋生物受到当地严格法律的保护。"],
"gulf": ["A narrow gulf separates the two countries.", "一条狭窄的海湾把这两个国家隔开。"],
"coast": ["We drove along the coast for the whole afternoon.", "我们整个下午都沿着海岸开车。"],
"shore": ["Children were building sandcastles on the shore.", "孩子们在岸边堆沙堡。"],
"tide": ["The tide comes in quickly, so do not leave your things on the sand.", "潮水涨得很快，别把东西放在沙滩上。"],
"current": ["The current here is too strong for inexperienced swimmers.", "这里的洋流对没有经验的游泳者来说太强了。"],
"brook": ["A small brook runs behind the farmhouse.", "农舍后面有一条小溪流过。"],
"stream": ["They followed the stream until it joined the river.", "他们沿着小溪走，直到它汇入大河。"],
"source": ["Investigators are still looking for the source of the leak.", "调查人员仍在寻找泄漏的源头。"],
"beach": ["We spent the morning walking along the empty beach.", "我们花了一上午在空荡荡的海滩上散步。"],
"steep": ["The road became too steep for the old truck to climb.", "路变得太陡，那辆旧卡车爬不上去。"],
"shallow": ["The water here is shallow enough for children to stand in.", "这里的水很浅，孩子们能站得住。"],
"parallel": ["The two roads run parallel to each other for several miles.", "这两条路平行延伸了好几英里。"],
"narrow": ["The narrow street was crowded with tourists.", "狭窄的街道上挤满了游客。"],
"flat": ["The land around the river is completely flat for miles.", "河流周围的土地绵延数英里都非常平坦。"],
"smooth": ["The lake surface was smooth as glass that morning.", "那天早上湖面平滑如镜。"],
"rough": ["The boat rocked violently in the rough sea.", "小船在波涛汹涌的海面上剧烈摇晃。"],
"mainland": ["The island is connected to the mainland by a long bridge.", "这座岛通过一座长桥与大陆相连。"],
"peninsula": ["The small town sits at the tip of a rocky peninsula.", "这座小镇位于多岩半岛的尖端。"],
"sandy": ["They parked the car beside a sandy track.", "他们把车停在一条沙质小路旁。"],
"climate": ["The climate here is too dry for most fruit trees.", "这里的气候对大多数果树来说太干燥了。"],
"stony": ["The farmer gave up trying to grow crops on the stony ground.", "农夫放弃了在多石的土地上种庄稼。"],
"vertical": ["The climbers faced a nearly vertical wall of rock.", "登山者面对的是一面近乎垂直的岩壁。"],
"mild": ["Winters in this part of the country are usually mild.", "该国这一带的冬天通常很温和。"],
"heating": ["The heating broke down during the coldest week of the year.", "暖气在一年中最冷的那一周坏了。"],
"warm": ["She warmed her hands by the fire before going out.", "出门前她在火边暖暖手。"],
"thermal": ["Visitors come to bathe in the thermal springs each winter.", "每年冬天游客都来泡温泉。"],
"tropics": ["Many spices grow best in the tropics.", "许多香料在热带长得最好。"],
"arid": ["Only a few hardy plants survive in this arid region.", "在这片干旱地区只有少数耐旱植物能存活。"],
"moist": ["Keep the soil moist but never soaking wet.", "让土壤保持湿润，但绝不能积水。"],
"damp": ["The walls of the old house felt cold and damp.", "老房子的墙壁摸起来又冷又潮。"],
"humid": ["Summers here are hot and humid, so people stay indoors at noon.", "这里的夏天又热又潮湿，所以中午人们都待在室内。"],
"snowy": ["The snowy road made driving slow and dangerous.", "积雪的道路让开车又慢又危险。"],
"frost": ["The first frost of the year covered the garden in white.", "今年的第一场霜把花园盖成一片白。"],
"hail": ["The hail was so large that it damaged several car roofs.", "冰雹太大了，砸坏了好几辆车的车顶。"],
"thaw": ["The thaw turned the frozen path into deep mud.", "融雪把冻住的小路变成了深泥。"],
"chill": ["There was a chill in the air that hinted at coming winter.", "空气中有股寒意，预示着冬天将至。"],
"freeze": ["The lake will freeze over by the end of December.", "湖面到十二月底就会结冰。"],
"frigid": ["They spent a week in the frigid conditions of the far north.", "他们在极北的严寒环境中待了一周。"],
"tremble": ["Her hands trembled as she opened the letter.", "她打开信时双手发抖。"],
"shiver": ["The children shivered in the cold wind while waiting for the bus.", "孩子们在冷风中等公交车，冻得发抖。"],
"thunder": ["The thunder rolled across the valley for nearly an hour.", "雷声在山谷中回荡了近一个小时。"],
"lightning": ["A flash of lightning lit up the whole sky.", "一道闪电照亮了整片天空。"],
"stormy": ["All flights were delayed because of the stormy weather.", "由于暴风雨天气，所有航班都延误了。"],
"downpour": ["We were caught in a sudden downpour without an umbrella.", "我们没带伞，被一场突如其来的倾盆大雨淋了个透。"],
"rainfall": ["The region receives very little rainfall in summer.", "该地区夏季降雨量很少。"],
"sprinkle": ["She sprinkled a little salt over the vegetables.", "她在蔬菜上撒了一点盐。"],
"rainbow": ["A rainbow appeared over the hills just after the rain stopped.", "雨刚停，一道彩虹就出现在山丘上空。"],
"temperature": ["The temperature dropped below zero during the night.", "夜间气温降到了零度以下。"],
"forecast": ["The forecast says it will clear up by the weekend.", "天气预报说到周末会放晴。"],
"peak": ["They reached the peak after eight hours of climbing.", "爬了八小时后他们登上了峰顶。"],
"mount": ["The museum mounted a special exhibition of ancient maps.", "博物馆举办了一场古地图特展。"],
"mountain": ["The village sits at the foot of a tall mountain.", "村庄坐落在一座高山的脚下。"],
"range": ["A long mountain range runs along the western border.", "一条长长的山脉沿西部边界延伸。"],
"ridge": ["We walked along the ridge for several hours.", "我们沿着山脊走了好几个小时。"],
"slope": ["The house was built on a gentle slope facing south.", "这栋房子建在朝南的缓坡上。"],
"valley": ["A river runs through the middle of the valley.", "一条河从山谷中间穿过。"],
"hillside": ["Sheep grazed quietly on the sunny hillside.", "羊群在向阳的山坡上安静地吃草。"],
"southern": ["The southern part of the country is warmer and wetter.", "该国南部更温暖也更潮湿。"],
"southeast": ["They sailed southeast for three days before sighting land.", "他们向东南航行了三天才看到陆地。"],
"southwest": ["A strong wind blew from the southwest all night.", "整夜都刮着西南风。"],
"northeast": ["The airport lies to the northeast of the city centre.", "机场位于市中心东北方向。"],
"eastern": ["The eastern coast is famous for its fishing villages.", "东部海岸以渔村闻名。"],
"oriental": ["The museum has a fine collection of oriental art.", "这座博物馆收藏着精美的东方艺术品。"],
"inevitable": ["Some disagreement is inevitable when so many people are involved.", "涉及这么多人时，有些分歧是不可避免的。"],
"irreversible": ["The damage to the forest may be irreversible.", "森林受到的破坏可能是不可逆的。"],
"irregularly": ["He slept irregularly during the exam period.", "考试期间他的睡眠很不规律。"],
"inappropriate": ["Wearing jeans to the interview would be inappropriate.", "穿牛仔裤去面试是不合适的。"],
"abnormal": ["The doctor found nothing abnormal in the test results.", "医生在检查结果中没发现任何异常。"],
"sediment": ["A layer of sediment settled at the bottom of the jar.", "一层沉淀物沉在罐子底部。"],
"silt": ["The harbour is slowly filling with silt.", "港口正慢慢被淤泥填满。"],
"muddy": ["The children came home with muddy boots.", "孩子们回家时靴子上全是泥。"],
"clay": ["Local potters shape the clay into bowls and vases.", "当地的陶工把黏土捏成碗和花瓶。"],
"dirt": ["He brushed the dirt off his coat before entering.", "进门之前他刷掉了外套上的灰。"],
"rural": ["Life in rural areas is quieter but offers fewer jobs.", "乡村生活更安静，但工作机会更少。"],
"suburb": ["They moved to a quiet suburb after their child was born.", "孩子出生后他们搬到了一个安静的郊区。"],
"outskirts": ["The factory stands on the outskirts of the city.", "工厂位于城市近郊。"],
"remote": ["The clinic serves several remote villages in the mountains.", "这家诊所为山区的几个偏远村庄提供服务。"],
"distant": ["From here you can see the distant outline of the islands.", "从这里能看到那些岛屿遥远的轮廓。"],
"adjacent": ["The library is adjacent to the main teaching building.", "图书馆紧邻主教学楼。"],
"toxic": ["The factory was fined for releasing toxic chemicals.", "这家工厂因排放有毒化学品被罚款。"],
"pollution": ["Air pollution in the city has fallen since the new rules began.", "新规实施以来，该市的空气污染有所下降。"],
"pollutant": ["The study measured several common air pollutants.", "这项研究测量了几种常见的空气污染物。"],
"contaminate": ["Waste from the mine could contaminate the river downstream.", "矿场废料可能污染下游的河水。"],
"border": ["They crossed the border early in the morning.", "他们一大早就过了边境。"],
"margin": ["Write your notes in the margin of the page.", "把笔记写在页边的空白处。"],
"fringe": ["A fringe of trees surrounds the field.", "一圈树木环绕着这片田地。"],
"plate": ["The geologist explained how the plates move under the surface.", "地质学家解释了板块如何在地表之下移动。"],
"debris": ["Workers cleared the debris left by the storm.", "工人们清理了风暴留下的残骸。"],
"crack": ["A long crack appeared in the wall after the earthquake.", "地震后墙上出现了一条长长的裂缝。"],
"gap": ["There is a narrow gap between the two buildings.", "两栋楼之间有一道窄缝。"],
"splendid": ["From the top we enjoyed a splendid view of the whole bay.", "从顶上我们饱览了整个海湾的壮丽景色。"],
"grand": ["They held the ceremony in a grand hall with high ceilings.", "他们在一个天花板高挑的宏伟大厅里举行了仪式。"],
"magnificent": ["The cathedral is magnificent both inside and out.", "这座大教堂内外都很壮观。"],
"super": ["The hotel room was super clean and surprisingly cheap.", "这间酒店房间超级干净，而且出奇地便宜。"],
"interesting": ["The guide told us several interesting facts about the lake.", "导游给我们讲了几个关于这个湖的趣闻。"],
"dramatic": ["There has been a dramatic change in the weather this week.", "这周天气发生了剧烈变化。"],
"wilderness": ["They spent ten days hiking through the wilderness.", "他们花了十天在荒野中徒步。"],
"deforest": ["Companies continue to deforest large areas for farming.", "公司仍在为开垦农田而大面积砍伐森林。"],
"barren": ["Nothing grows on this barren hillside.", "这片贫瘠的山坡上什么也长不出来。"],
"fertile": ["The fertile soil near the river yields two crops a year.", "河边肥沃的土壤一年能收两季庄稼。"],
"fertilise": ["Farmers fertilise the fields before the rainy season.", "农民在雨季前给田地施肥。"],
"solar": ["The house is heated entirely by solar energy.", "这栋房子完全靠太阳能供暖。"],
"lunar": ["The lunar calendar is still used for traditional festivals.", "农历仍被用于传统节日。"],
"calendar": ["I marked the deadline on my calendar.", "我把截止日期标在了日历上。"],
"sunrise": ["We got up before sunrise to catch the ferry.", "我们日出前就起床去赶渡轮。"],
"sunset": ["The sunset turned the whole sky orange and pink.", "日落把整片天空染成橙粉色。"],
"dusk": ["Bats begin to fly at dusk.", "蝙蝠在黄昏时开始飞出来。"],
"heaven": ["After a long week, a quiet evening at home felt like heaven.", "忙碌一周后，在家安静度过一晚感觉像天堂。"],
"paradise": ["The island is a paradise for bird watchers.", "这座岛是观鸟者的乐园。"],
"sunshine": ["We sat in the sunshine and talked for hours.", "我们坐在阳光下聊了好几个小时。"],
"shade": ["They rested in the shade of a large tree.", "他们在一棵大树的阴凉处休息。"],
"shadow": ["His shadow stretched across the pavement in the evening light.", "暮色中他的影子投在人行道上。"],
"vapour": ["Water vapour rises from the warm surface of the lake.", "水汽从温暖的湖面升起。"],
"evaporate": ["Most of the water will evaporate in this heat.", "在这样的高温下，大部分水都会蒸发。"],
"circulate": ["Open the windows to let the air circulate.", "打开窗户让空气流通。"],
"reservoir": ["The city draws its water from a reservoir in the hills.", "这座城市的水来自山中的水库。"],
"waterfall": ["The waterfall drops nearly a hundred metres into the pool below.", "瀑布落差近百米，落入下方的水潭。"],
"fountain": ["Children played beside the fountain in the square.", "孩子们在广场的喷泉边玩耍。"],
"spring": ["A natural spring provides water for the whole village.", "一眼天然泉水为整个村子供水。"],
"dew": ["In the early morning the grass was wet with dew.", "清晨草地上沾满了露水。"],
"pour": ["She poured the tea carefully into three cups.", "她小心地把茶倒进三个杯子。"],
"drain": ["The rainwater drains away through pipes under the road.", "雨水通过路面下的管道排走。"],
"drip": ["The tap has been dripping all night.", "水龙头滴了一整夜。"],
"drown": ["Two swimmers nearly drowned in the strong current.", "两名游泳者差点在急流中淹死。"],
"blow": ["The wind blew the door shut with a loud bang.", "风砰的一声把门吹上了。"],
"puff": ["A puff of smoke rose from the chimney.", "一缕烟从烟囱里升起。"],
"dense": ["The village was hidden by dense forest.", "村庄被茂密的森林遮住了。"],
"intensity": ["The intensity of the storm surprised even the forecasters.", "这场风暴的强度连预报员都感到意外。"],
"intensive": ["She took an intensive course in English before going abroad.", "出国前她上了一个英语强化课程。"],
"emerge": ["The sun emerged from behind the clouds at last.", "太阳终于从云后露了出来。"],
"flash": ["A light flashed twice in the distance.", "远处有一道光闪了两下。"],
"float": ["Leaves floated slowly down the stream.", "树叶缓缓地顺流漂下。"],
"environment": ["The new law is designed to protect the environment.", "这部新法律旨在保护环境。"],
"surrounding": ["The surrounding countryside is perfect for cycling.", "周边的乡野非常适合骑自行车。"],
"condition": ["The road conditions were poor after the heavy rain.", "大雨过后路况很差。"],
"gush": ["Water gushed from the broken pipe and flooded the street.", "水从破裂的管道喷涌而出，淹了街道。"],
"nature": ["Walking in nature helps me clear my mind.", "在大自然中散步能让我理清思绪。"],
"natural": ["The cave was formed by natural processes over thousands of years.", "这个洞穴是数千年自然作用形成的。"],
"artificial": ["The lake is artificial and was dug about fifty years ago.", "这个湖是人工挖的，大约五十年前建成。"],
"synthetic": ["This jacket is made of synthetic fibres that dry quickly.", "这件夹克由速干的合成纤维制成。"],
"petrol": ["The car ran out of petrol halfway home.", "车在回家途中没油了。"],
"gas": ["Natural gas is used for cooking in most homes here.", "这里大多数家庭用天然气做饭。"],
"gasoline": ["Gasoline prices rose again this month.", "本月汽油价格又上涨了。"],
"petroleum": ["The country's economy depends heavily on petroleum exports.", "该国经济严重依赖石油出口。"]
};
