module.exports = {
"photosynthesis": ["Plants use sunlight to carry out photosynthesis and produce food.", "植物利用阳光进行光合作用并制造养分。"],
"respire": ["Fish respire through their gills by taking oxygen from the water.", "鱼通过鳃从水中吸取氧气进行呼吸。"],
"dioxide": ["Too much carbon dioxide in the air traps heat in the atmosphere.", "空气中过多的二氧化碳会把热量留在大气里。"],
"vegetation": ["Thick vegetation covers most of the island's interior.", "茂密的植被覆盖了这座岛的大部分内陆地区。"],
"herb": ["She grows several kinds of herb in pots on the balcony.", "她在阳台的花盆里种了好几种香草。"],
"perennial": ["These perennial plants come back every spring without replanting.", "这些多年生植物每年春天都会重新长出，不用重种。"],
"botany": ["He studied botany at university and now works in a garden.", "他大学学的是植物学，现在在一座植物园工作。"],
"ecology": ["The course covers the ecology of tropical forests.", "这门课讲授热带森林的生态。"],
"ecosystem": ["A single oil spill can damage the whole marine ecosystem.", "一次石油泄漏就可能破坏整个海洋生态系统。"],
"horticulture": ["She took a course in horticulture to learn how to grow roses.", "她上了园艺课，学习怎么种玫瑰。"],
"organism": ["Every living organism needs water to survive.", "每一种生物都需要水才能生存。"],
"genetics": ["Recent advances in genetics have changed how doctors treat some diseases.", "遗传学的新进展改变了医生治疗某些疾病的方式。"],
"mutation": ["A random mutation can sometimes help a species adapt.", "随机的突变有时能帮助一个物种适应环境。"],
"variation": ["There is wide variation in rainfall from year to year.", "各年降雨量差异很大。"],
"diversity": ["The forest is famous for the diversity of its bird life.", "这片森林以其鸟类的多样性闻名。"],
"classify": ["Scientists classify these plants by the shape of their leaves.", "科学家按叶子的形状给这些植物分类。"],
"reproduce": ["Many plants reproduce by spreading seeds in the wind.", "许多植物通过随风散播种子来繁殖。"],
"evolve": ["Species must evolve to survive in a changing climate.", "物种必须进化才能在变化的气候中生存。"],
"fluctuate": ["Vegetable prices fluctuate a lot depending on the season.", "蔬菜价格随季节波动很大。"],
"reclaim": ["The project aims to reclaim desert land for farming.", "这个项目旨在把荒漠土地改造成农田。"],
"cultivate": ["Farmers here cultivate rice on terraced hillsides.", "这里的农民在梯田上种植水稻。"],
"harvest": ["They harvest the grapes by hand in early autumn.", "他们在初秋手工采摘葡萄。"],
"pluck": ["She plucked a ripe apple from the tree.", "她从树上摘下一个熟苹果。"],
"pick": ["Visitors are allowed to pick their own strawberries.", "游客可以自己采草莓。"],
"yield": ["Good rainfall this year produced a record yield of wheat.", "今年雨水充沛，小麦产量创下纪录。"],
"rear": ["The family rears cattle on the hills above the village.", "这家人在村子上面的山坡上养牛。"],
"arable": ["Only a small part of the country is arable land.", "这个国家只有一小部分是耕地。"],
"plough": ["Farmers plough the fields before the spring planting.", "农民在春播前犁地。"],
"spade": ["He dug the vegetable patch with an old spade.", "他用一把旧铁锹翻松了菜地。"],
"rake": ["She used a rake to gather the fallen leaves.", "她用耙子把落叶拢在一起。"],
"stack": ["They stacked the hay neatly at the edge of the field.", "他们把干草整齐地堆在田边。"],
"heap": ["A heap of logs lay beside the fireplace.", "壁炉旁堆着一堆木柴。"],
"bundle": ["He carried a bundle of firewood on his back.", "他背着一捆柴火。"],
"bunch": ["She bought a bunch of fresh flowers for the table.", "她买了一束鲜花摆在桌上。"],
"vase": ["The roses look lovely in that blue vase.", "玫瑰插在那个蓝花瓶里很好看。"],
"sunlight": ["The room gets plenty of sunlight in the morning.", "这个房间早上阳光充足。"],
"short-day": ["Short-day plants flower only when the nights are long.", "短日照植物只在夜间较长时开花。"],
"shade-tolerant": ["Shade-tolerant species can grow under a thick forest canopy.", "耐阴的物种能在茂密的林冠下生长。"],
"fungus": ["This fungus grows on dead wood after heavy rain.", "这种真菌在大雨后长在枯木上。"],
"mould": ["Mould had begun to form on the old bread.", "那块放久的面包上开始长霉了。"],
"pollen": ["Bees carry pollen from one flower to another.", "蜜蜂把花粉从一朵花带到另一朵花。"],
"germinate": ["The seeds germinate about ten days after planting.", "种子在播种约十天后发芽。"],
"seed": ["She planted a few seed in each small pot.", "她在每个小盆里播了几粒种子。"],
"burgeon": ["The young tree will burgeon into a thick canopy within years.", "这棵小树几年内就会长成茂密的树冠。"],
"bud": ["Tiny green buds appeared on the branches in March.", "三月里树枝上冒出了小小的绿芽。"],
"blossom": ["The cherry trees blossom for only a couple of weeks.", "樱花树只开花两周左右。"],
"bloom": ["The roses bloom twice a year in this garden.", "这个园子里的玫瑰一年开两次花。"],
"scent": ["The scent of jasmine filled the whole courtyard.", "茉莉的香气弥漫了整个院子。"],
"aromatic": ["Basil is an aromatic herb often used in cooking.", "罗勒是一种常用于烹饪的香草。"],
"ripen": ["Tomatoes ripen faster in a warm, sunny spot.", "番茄在温暖向阳的地方熟得更快。"],
"fruit": ["The apple trees fruit heavily every second year.", "这些苹果树隔年结一次大丰收。"],
"wither": ["The flowers withered within days in the heat.", "花在高温下几天就枯萎了。"],
"decompose": ["Leaves decompose slowly and enrich the soil.", "落叶慢慢腐烂，使土壤更肥沃。"],
"rot": ["The wooden fence had begun to rot at the base.", "木栅栏的底部已经开始腐烂。"],
"decay": ["Fallen fruit will decay quickly in the summer heat.", "掉落的果实在夏日高温下很快就会腐坏。"],
"stale": ["The bread had gone stale by the third day.", "到第三天面包已经不新鲜了。"],
"rainforest": ["Thousands of species live in the rainforest canopy.", "数以千计的物种生活在雨林林冠层中。"],
"jungle": ["They cut a narrow path through the dense jungle.", "他们在茂密的丛林里开出一条窄路。"],
"plantation": ["The tea plantation stretches across the hillside.", "茶园绵延整个山坡。"],
"field": ["The wheat field turned golden by the end of June.", "到了六月底麦田变成了金黄色。"],
"terrace": ["Rice is grown on terraces cut into the hillside.", "水稻种在山坡上开出的梯田里。"],
"timber": ["The house was built from locally produced timber.", "这栋房子是用当地出产的木材建造的。"],
"charcoal": ["They cooked the fish over a small charcoal fire.", "他们在小小的炭火上烤鱼。"],
"log": ["He split the log into four pieces with an axe.", "他用斧子把圆木劈成四块。"],
"logo": ["The company changed its logo to look more modern.", "公司更换了标志，看起来更现代。"],
"forestry": ["Forestry provides work for many families in this region.", "林业为这个地区的许多家庭提供了工作。"],
"branch": ["A heavy branch broke off during the storm.", "一根粗树枝在暴风雨中折断了。"],
"trunk": ["The trunk of that oak is almost two metres wide.", "那棵橡树的树干将近两米粗。"],
"bough": ["Birds were singing on the topmost bough.", "鸟儿在最上面的树枝上歌唱。"],
"root": ["The roots of the tree reach deep into the soil.", "这棵树的根深深扎进土壤里。"],
"hay": ["The farmer stored the hay in the barn for winter.", "农夫把干草贮存在谷仓里过冬。"],
"straw": ["The baskets are woven from dried straw.", "这些篮子是用干草编的。"],
"reed": ["Tall reeds grow along the edge of the pond.", "池塘边生长着高高的芦苇。"],
"thorn": ["A sharp thorn stuck in the sole of his shoe.", "一根尖刺扎进了他的鞋底。"],
"weed": ["She spent the morning pulling weeds out of the flower bed.", "她花了一上午拔花坛里的杂草。"],
"grass": ["The children played on the grass in front of the house.", "孩子们在屋前的草地上玩耍。"],
"meadow": ["Wild flowers covered the meadow in early summer.", "初夏时野花铺满了草地。"],
"lawn": ["He mows the lawn every Saturday morning.", "他每周六早上修剪草坪。"],
"olive": ["The region is known for its olive groves.", "这个地区以橄榄园闻名。"],
"pine": ["A line of pine trees sheltered the house from the wind.", "一排松树为房子挡住了风。"],
"vine": ["Grapes grow on vines trained along wires.", "葡萄长在沿着铁丝牵引的藤上。"],
"violet": ["Small violet flowers appeared between the stones.", "石头之间开出了紫色的小花。"],
"tulip": ["The tulips in the park are at their best in April.", "公园里的郁金香在四月最好看。"],
"mint": ["She added fresh mint to the cold drink.", "她在冷饮里加了新鲜薄荷。"],
"reef": ["The coral reef supports an astonishing variety of fish.", "珊瑚礁养育着种类惊人的鱼类。"],
"alga": ["This alga grows rapidly in warm, nutrient-rich water.", "这种藻类在温暖富营养的水中繁殖很快。"],
"enzyme": ["Enzymes in the stomach help break down food.", "胃里的酶帮助分解食物。"],
"catalyst": ["The new policy acted as a catalyst for change.", "这项新政策成了推动变革的催化剂。"],
"emission": ["The country plans to cut carbon emissions by half.", "该国计划把碳排放削减一半。"],
"absorb": ["Plants absorb water through their roots.", "植物通过根部吸收水分。"],
"circulation": ["Regular exercise improves blood circulation.", "规律运动能改善血液循环。"],
"exceed": ["Demand for water may exceed supply in dry years.", "干旱年份的用水需求可能超过供给。"],
"uptake": ["The uptake of new farming methods has been slow.", "新耕作方法的采用一直很缓慢。"],
"nutrient": ["Fruit and vegetables are rich in nutrients.", "水果和蔬菜富含营养。"],
"energy": ["Solar panels convert sunlight into electrical energy.", "太阳能板把阳光转换成电能。"],
"surroundings": ["The animals soon adapted to their new surroundings.", "这些动物很快适应了新环境。"],
"mechanism": ["The plant has a clever mechanism for trapping insects.", "这种植物有一套巧妙的捕虫机制。"],
"protect": ["The fence was built to protect young trees from deer.", "围栏是为了保护幼树不被鹿啃食。"],
"preserve": ["The trust works to preserve the old woodland.", "这家信托机构致力于保护这片古老林地。"],
"conservation": ["Wildlife conservation depends on protecting habitats.", "野生动物保护取决于对栖息地的保护。"],
"bush fire": ["A bush fire destroyed thousands of hectares of forest.", "一场丛林大火烧毁了数千公顷森林。"],
"extinguish": ["Firefighters worked all night to extinguish the flames.", "消防员奋战整夜扑灭火焰。"],
"destruct": ["The missile can destruct itself if the launch is aborted.", "如果发射中止，导弹可以自毁。"],
"ruin": ["Heavy rain ruined the newly planted crops.", "大雨毁掉了新种的庄稼。"],
"perish": ["Many young plants perish in the first cold spell.", "许多幼苗在第一次寒潮中就冻死了。"],
"demolish": ["The old factory will be demolished next month.", "那座旧工厂下个月将被拆除。"],
"undermine": ["Constant flooding undermines the foundations of the bridge.", "反复的洪水侵蚀着桥的地基。"],
"extinction": ["Several bird species here face extinction.", "这里的几种鸟类面临灭绝。"],
"pattern": ["The leaves grow in a regular pattern around the stem.", "叶子绕着茎按规律的图案生长。"],
"outcome": ["The outcome of the experiment surprised the researchers.", "实验结果让研究人员感到意外。"],
"productive": ["The farm is most productive in the cooler months.", "这个农场在较凉的月份产量最高。"],
"effective": ["This method proved far more effective than the old one.", "这个方法证明比旧的更有效。"],
"efficient": ["The new irrigation system is more efficient and uses less water.", "新灌溉系统更高效，用水更少。"],
"considerable": ["A considerable amount of rain fell during the night.", "夜里下了相当大的雨。"],
"massive": ["A massive tree blocked the road after the storm.", "暴风雨后一棵巨大的树挡住了路。"],
"immense": ["The desert stretches across an immense area.", "沙漠绵延在一片广袤的区域上。"],
"seasonal": ["Picking fruit is seasonal work for many local families.", "采果对许多当地家庭来说是季节性工作。"],
"experimental": ["The experimental field was divided into six plots.", "实验田被分成六块。"],
"favourable": ["The warm spring created favourable conditions for growth.", "温暖的春天为生长创造了有利条件。"],
"maximal": ["Plants reach maximal height in the wettest months.", "植物在最湿润的月份达到最高生长量。"],
"minimal": ["The plants need only minimal care once established.", "这些植物一旦成活只需极少的照料。"],
"optimal": ["These trees grow best at an optimal temperature of around twenty degrees.", "这些树在约二十度的最佳温度下长得最好。"]
};
