module.exports = {
"biologist": ["The biologist spent three years studying birds on the island.", "这位生物学家在岛上花了三年研究鸟类。"],
"zoologist": ["A zoologist explained how the elephant uses its trunk.", "一位动物学家解释了象如何使用它的鼻子。"],
"botanist": ["The botanist collected samples of every plant in the valley.", "植物学家采集了山谷里每一种植物的样本。"],
"mammal": ["The whale is the largest mammal in the ocean.", "鲸是海洋中最大的哺乳动物。"],
"primate": ["Monkeys and apes belong to the primate group.", "猴和猿都属于灵长类。"],
"vertebrate": ["Every vertebrate has a backbone of some kind.", "每一种脊椎动物都有某种形式的脊柱。"],
"reptile": ["Snakes and lizards are cold-blooded reptiles.", "蛇和蜥蜴是冷血的爬行动物。"],
"amphibian": ["Frogs are amphibians that live both in water and on land.", "青蛙是既生活在水中又生活在陆地上的两栖动物。"],
"carnivore": ["The lion is a carnivore that hunts large animals.", "狮子是捕猎大型动物的食肉动物。"],
"herbivore": ["Deer are herbivores that feed mainly on leaves and grass.", "鹿是主要以树叶和草为食的食草动物。"],
"flock": ["A flock of geese flew over the lake at dawn.", "黎明时一群大雁飞过湖面。"],
"creature": ["The camera captured a small creature moving through the grass.", "相机拍到了一只小生物在草丛中移动。"],
"throng": ["A throng of visitors filled the square by noon.", "到中午广场上挤满了游客。"],
"wildlife": ["The reserve protects wildlife from hunting and pollution.", "这个保护区保护野生动物免受捕猎和污染。"],
"crowd": ["A crowd gathered to watch the elephants being fed.", "一群人聚拢来观看大象进食。"],
"fauna": ["The island's fauna includes several species found nowhere else.", "岛上的动物群包括几种别处没有的物种。"],
"beast": ["Local people still tell stories about a beast in the forest.", "当地人至今还在讲森林里野兽的故事。"],
"flora": ["The flora of this region changes with altitude.", "这个地区的植物群随海拔变化。"],
"brute": ["The horse was a powerful brute but surprisingly gentle.", "这匹马强壮有力，却出奇地温顺。"],
"cruel": ["It is cruel to keep such a large animal in a small cage.", "把这么大的动物关在小笼子里很残忍。"],
"species": ["Several species of frog have disappeared from this area.", "这个地区已有几种蛙类消失。"],
"originate": ["These birds originate from the mountains of central Asia.", "这些鸟起源于中亚的山地。"],
"derive": ["Many modern crops derive from wild grasses.", "许多现代作物源于野生禾草。"],
"herd": ["A herd of cattle grazed quietly on the hillside.", "一群牛在山坡上安静地吃草。"],
"stem": ["Most of the fruit we eat stems from wild varieties.", "我们吃的大部分水果都源自野生品种。"],
"swarm": ["A swarm of bees settled on the branch.", "一群蜜蜂落在树枝上。"],
"ancestor": ["The modern horse has a much smaller ancestor.", "现代马的祖先体型要小得多。"],
"descendant": ["This bird is a descendant of dinosaurs.", "这种鸟是恐龙的后代。"],
"offspring": ["Most birds feed their offspring for several weeks.", "大多数鸟要喂养幼鸟好几周。"],
"subgroup": ["Researchers identified a small subgroup within the population.", "研究人员在这一种群中识别出一个小的亚群。"],
"feed": ["The keepers feed the seals twice a day.", "饲养员每天喂海豹两次。"],
"breed": ["These birds breed only on a few remote islands.", "这些鸟只在少数偏远岛屿上繁殖。"],
"interbreed": ["The two species rarely interbreed in the wild.", "这两个物种在野外很少杂交。"],
"hybridise": ["Farmers hybridise crops to improve their yield.", "农民通过杂交作物来提高产量。"],
"proliferate": ["Rabbits proliferate quickly when there are no predators.", "没有天敌时兔子繁殖很快。"],
"sterility": ["The sterility of the soil makes farming difficult here.", "土壤贫瘠让这里务农很困难。"],
"courtship": ["The male bird performs an elaborate courtship display.", "雄鸟会进行复杂的求偶表演。"],
"lay": ["Sea turtles lay their eggs on the same beach every year.", "海龟每年都在同一片沙滩上产卵。"],
"hatch": ["The eggs will hatch in about three weeks.", "这些卵大约三周后孵化。"],
"fin": ["The shark's fin broke the surface of the water.", "鲨鱼的鳍划破了水面。"],
"wing": ["The injured bird could not move its left wing.", "这只受伤的鸟动不了左翅。"],
"brood": ["The mother bird sat on the brood to keep it warm.", "母鸟卧在一窝雏鸟上为它们保暖。"],
"spawn": ["Salmon return to the river where they were born to spawn.", "鲑鱼回到出生的河流产卵。"],
"mature": ["These animals mature slowly and live for many years.", "这些动物成熟缓慢，寿命很长。"],
"skin": ["The elephant's skin is thick but very sensitive.", "大象的皮很厚，却非常敏感。"],
"claw": ["The eagle caught the fish with its sharp claws.", "老鹰用利爪抓住了鱼。"],
"paw": ["The dog held up its injured paw.", "狗抬起了受伤的爪子。"],
"beak": ["The bird used its beak to break the shell.", "鸟用喙敲破了壳。"],
"plume": ["The peacock spread its colourful plumes.", "孔雀展开了绚丽的羽毛。"],
"feather": ["She found a single white feather on the path.", "她在小路上发现了一根白色的羽毛。"],
"fur": ["The fox has thick fur to survive the winter.", "狐狸有厚实的毛皮来度过冬天。"],
"bristle": ["The hedgehog's bristles stood up when it was frightened.", "刺猬受惊时身上的刺竖了起来。"],
"curl": ["The lamb's wool formed tight curls.", "小羊的毛卷成了紧密的卷。"],
"insect": ["The forest is home to thousands of insect species.", "这片森林是数千种昆虫的家园。"],
"worm": ["Earthworms help keep the soil healthy.", "蚯蚓有助于保持土壤健康。"],
"pest": ["Farmers use natural methods to control pests.", "农民用自然方法防治害虫。"],
"parasite": ["This parasite lives on the feathers of large birds.", "这种寄生虫生活在大鸟的羽毛上。"],
"tortoise": ["The tortoise moved slowly across the garden.", "陆龟慢慢地穿过花园。"],
"turtle": ["We watched a turtle swim past the boat.", "我们看着一只海龟从船边游过。"],
"whale": ["Blue whales can be heard from several kilometres away.", "蓝鲸的声音在几公里外都能听到。"],
"spider": ["A spider had built its web between the two branches.", "一只蜘蛛在两根树枝间结了网。"],
"butterfly": ["The butterfly rested on a yellow flower.", "蝴蝶停在一朵黄花上。"],
"mosquito": ["Mosquito bites are common near standing water.", "在积水附近常被蚊子叮咬。"],
"cricket": ["The sound of crickets filled the summer night.", "蟋蟀的鸣叫声充满了夏夜。"],
"penguin": ["Penguins huddle together to stay warm in the wind.", "企鹅挤在一起在风中保暖。"],
"seal": ["A seal lay sunning itself on the rocks.", "一只海豹躺在岩石上晒太阳。"],
"kangaroo": ["The kangaroo carried its young in a pouch.", "袋鼠把幼崽放在育儿袋里。"],
"camel": ["Camels can travel for days without drinking.", "骆驼可以数天不喝水地行走。"],
"panda": ["The panda spends most of the day eating bamboo.", "熊猫一天大部分时间都在吃竹子。"],
"elephant": ["Elephants use their trunks to pick up food and water.", "大象用鼻子取食物和水。"],
"pup": ["The seal pup stayed close to its mother.", "小海豹紧挨着母亲。"],
"lamb": ["The lambs were born in early spring.", "小羊在早春出生。"],
"ivory": ["The sale of ivory has been banned in many countries.", "许多国家已禁止象牙交易。"],
"horn": ["The rhino uses its horn mainly for defence.", "犀牛主要用角来自卫。"],
"cattle": ["Cattle need a lot of water in hot weather.", "天热时牛需要大量饮水。"],
"ox": ["The farmer used an ox to pull the plough.", "农夫用牛拉犁。"],
"bear": ["A bear can smell food from a long distance.", "熊在很远处就能闻到食物。"],
"bull": ["The bull lowered its head and refused to move.", "公牛低下头，不肯移动。"],
"wolf": ["Wolves hunt in packs during the winter.", "狼在冬天成群捕猎。"],
"buffalo": ["A herd of buffalo crossed the river slowly.", "一群水牛缓缓渡过河。"],
"dragon": ["Dragons appear in the legends of many cultures.", "龙出现在许多文化的传说中。"],
"horse": ["The horse was trained to carry riders across rough ground.", "这匹马受过训练，能载人穿越崎岖地面。"],
"fox": ["A fox slipped quietly through the hedge.", "一只狐狸悄悄穿过树篱。"],
"zebra": ["Zebras graze beside the giraffes on the plain.", "斑马和长颈鹿一起在平原上吃草。"],
"cub": ["The lion cub followed its mother everywhere.", "小狮子处处跟着母亲。"],
"donkey": ["The donkey carried the load up the narrow path.", "驴驮着货物走上狭窄的小路。"],
"calf": ["The calf stayed close to the herd.", "小牛紧跟着牛群。"],
"saddle": ["She adjusted the saddle before setting off.", "出发前她调整了马鞍。"],
"crow": ["A crow perched on the fence and watched us.", "一只乌鸦停在栅栏上看着我们。"],
"harness": ["The dog wore a harness instead of a collar.", "这只狗戴的是胸背带而不是项圈。"],
"falcon": ["The falcon dived towards the ground at great speed.", "猎鹰以极快的速度俯冲向地面。"],
"hawk": ["A hawk circled slowly above the field.", "一只鹰在田野上方缓慢盘旋。"],
"eagle": ["The eagle built its nest high on the cliff.", "鹰把巢筑在悬崖高处。"],
"owl": ["An owl called from somewhere in the darkness.", "黑暗中某处传来猫头鹰的叫声。"],
"swallow": ["Swallows return to the same nest each spring.", "燕子每年春天回到同一个巢。"],
"sparrow": ["A sparrow landed on the windowsill.", "一只麻雀落在窗台上。"],
"pigeon": ["Pigeons gathered around the bread crumbs.", "鸽子聚在面包屑周围。"],
"swan": ["A swan glided across the still water.", "一只天鹅滑过平静的水面。"],
"goose": ["The goose chased anyone who came near its nest.", "这只鹅会追赶任何靠近它巢的人。"],
"cock": ["The cock crowed long before sunrise.", "公鸡在日出前很久就打鸣了。"],
"rat": ["Rats can squeeze through very narrow gaps.", "老鼠能钻过很窄的缝隙。"],
"squirrel": ["A squirrel buried nuts in the garden.", "一只松鼠把坚果埋在了花园里。"],
"hare": ["The hare ran faster than the dog could follow.", "野兔跑得比狗追得还快。"],
"frog": ["Frogs begin calling after the first warm rain.", "第一场暖雨后青蛙开始鸣叫。"],
"behaviour": ["Scientists study animal behaviour in the wild.", "科学家研究野生动物在野外的行为。"],
"bite": ["The snake's bite can be dangerous if untreated.", "蛇咬伤若不处理可能很危险。"],
"sting": ["A bee sting can be painful for several hours.", "被蜜蜂蜇后可能疼好几个小时。"],
"bark": ["The dog's bark warned us someone was coming.", "狗叫声提醒我们有人来了。"],
"roar": ["The lion's roar could be heard across the valley.", "狮子的吼声整个山谷都能听到。"],
"rub": ["The bear rubbed its back against the tree.", "熊在树上蹭背。"],
"creep": ["The cat crept towards the bird without a sound.", "猫悄无声息地朝鸟潜行。"],
"crawl": ["The beetle crawled slowly across the path.", "甲虫缓慢地爬过小路。"],
"habitat": ["Draining the wetland destroyed the birds' habitat.", "排干湿地破坏了鸟类的栖息地。"],
"nest": ["The wasps built a nest under the roof.", "黄蜂在屋檐下筑了巢。"],
"hive": ["Thousands of bees live in a single hive.", "一个蜂巢里住着数千只蜜蜂。"],
"cell": ["The microscope showed the structure of a single cell.", "显微镜显示了单个细胞的结构。"],
"cage": ["The birds were moved to a much larger cage.", "这些鸟被移到了大得多的笼子里。"],
"stable": ["The horses were led back to the stable at dusk.", "黄昏时马被带回马厩。"],
"hedge": ["Birds nested in the thick hedge along the lane.", "鸟在小路旁茂密的树篱中筑巢。"],
"barrier": ["The fence acts as a barrier between the farm and the road.", "这道围栏成了农场与公路之间的屏障。"],
"bar": ["The zoo installed metal bars around the enclosure.", "动物园在围栏周围装了金属栏杆。"],
"anatomy": ["Students learn the anatomy of a fish in the first term.", "学生第一学期学习鱼的解剖结构。"],
"epidemic": ["An epidemic among the birds spread quickly last year.", "去年鸟群中的一场流行病迅速蔓延。"],
"gene": ["Scientists identified the gene responsible for the colour.", "科学家确定了决定这种颜色的基因。"],
"germ": ["Washing your hands removes most germs.", "洗手能去除大部分细菌。"],
"bacteria": ["Some bacteria in the soil help plants grow.", "土壤中的一些细菌有助于植物生长。"],
"virus": ["This virus affects only a few bird species.", "这种病毒只影响少数几种鸟。"],
"microbe": ["Microbes in the pond are too small to see.", "池塘里的微生物小得看不见。"],
"metabolism": ["Cold weather slows down an animal's metabolism.", "寒冷天气会减慢动物的新陈代谢。"],
"protein": ["Insects are an important source of protein for many birds.", "昆虫是许多鸟类重要的蛋白质来源。"],
"vitamin": ["Fresh plants provide the vitamins these animals need.", "新鲜植物提供这些动物所需的维生素。"],
"functional": ["The wings of this bird are no longer functional.", "这种鸟的翅膀已经丧失了功能。"],
"secrete": ["Some frogs secrete a substance that protects their skin.", "有些青蛙会分泌一种保护皮肤的物质。"],
"excrete": ["The kidneys excrete waste from the blood.", "肾脏把废物从血液中排出。"],
"devour": ["The snake devoured the whole egg in seconds.", "蛇几秒钟就把整颗蛋吞了下去。"],
"intuitive": ["Birds seem to have an intuitive sense of direction.", "鸟类似乎有一种直觉的方向感。"],
"potential": ["The forest has great potential for wildlife research.", "这片森林在野生动物研究上潜力很大。"],
"intelligence": ["Studies show that some birds have surprising intelligence.", "研究表明有些鸟的智力出人意料。"],
"sensitive": ["A cat's whiskers are extremely sensitive to touch.", "猫的胡须对触碰极其敏感。"],
"flexible": ["The snake's body is flexible enough to enter small holes.", "蛇的身体灵活得能钻进小洞。"],
"acoustic": ["Bats use acoustic signals to find their way in the dark.", "蝙蝠用声学信号在黑暗中辨向。"],
"optical": ["The insect's optical system is quite different from ours.", "这种昆虫的视觉系统和我们很不一样。"],
"nocturnal": ["Owls are nocturnal and hunt mainly at night.", "猫头鹰是夜行动物，主要在夜间捕猎。"],
"dormant": ["The seeds remain dormant until the soil warms up.", "种子在土壤变暖前一直处于休眠状态。"],
"hibernation": ["The bear's hibernation lasts about five months.", "熊的冬眠大约持续五个月。"],
"track": ["Researchers track the animals using radio collars.", "研究人员用无线电项圈追踪这些动物。"],
"trace": ["The hunters found traces of the animal near the river.", "猎人在河边发现了这种动物的踪迹。"],
"prey": ["The eagle scans the ground for prey.", "鹰扫视地面寻找猎物。"],
"predator": ["Without natural predators, the rabbits multiplied quickly.", "没有天敌，兔子迅速繁殖。"],
"victim": ["The weakest animals are usually the first victims.", "最弱的动物通常最先成为受害者。"],
"captive": ["The birds were bred in captive conditions for ten years.", "这些鸟在圈养条件下繁殖了十年。"],
"defensive": ["The porcupine's quills are purely defensive.", "豪猪的刺纯粹用于防御。"],
"undergo": ["The insects undergo several stages before becoming adults.", "这些昆虫在成为成虫前要经历几个阶段。"],
"suffer": ["Many species suffer when their habitat is destroyed.", "栖息地被破坏时，许多物种都会受害。"],
"vulnerable": ["Young animals are especially vulnerable to cold.", "幼兽尤其容易受寒。"],
"subsistence": ["These communities rely on subsistence hunting and fishing.", "这些社区依靠自给自足的狩猎和捕鱼为生。"],
"exist": ["Only a few hundred of these birds still exist.", "这种鸟现存的只有几百只。"],
"exterminate": ["Farmers once tried to exterminate the wolves in this area.", "农民曾试图消灭这一带的狼。"],
"tame": ["The fox gradually became tame enough to approach.", "这只狐狸渐渐驯服到可以靠近。"],
"keeper": ["The keeper has looked after the elephants for twenty years.", "这位饲养员照料大象已有二十年。"],
"shepherd": ["The shepherd led the flock down from the hills at dusk.", "黄昏时牧羊人把羊群从山上赶下来。"]
};
