module.exports = {
"galaxy": ["Our galaxy contains hundreds of billions of stars.", "我们的星系包含数千亿颗恒星。"],
"cosmos": ["Astronomers study the structure of the cosmos.", "天文学家研究宇宙的结构。"],
"universe": ["The universe is thought to be expanding.", "人们认为宇宙正在膨胀。"],
"astronomy": ["She became interested in astronomy after seeing a meteor shower.", "她在看过一场流星雨后对天文学产生了兴趣。"],
"astrology": ["Astrology is not considered a science today.", "占星术今天不再被视为科学。"],
"astronaut": ["The astronaut spent six months on the space station.", "这位宇航员在空间站待了六个月。"],
"comet": ["The comet will not return for another seventy years.", "这颗彗星七十年后才会再次出现。"],
"meteorite": ["A meteorite crashed into the desert last summer.", "去年夏天一块陨石坠入沙漠。"],
"crater": ["The telescope revealed a large crater on the moon's surface.", "望远镜显示出月球表面一个巨大的环形山。"],
"terrestrial": ["The probe sent back detailed images of the terrestrial surface.", "探测器发回了陆地表面的详细图像。"],
"celestial": ["Ancient sailors used celestial bodies to find their way.", "古代水手靠天体来辨别方向。"],
"dust": ["Fine dust from the comet spread across the sky.", "来自彗星的细小尘埃散布天空。"],
"ash": ["Volcanic ash drifted hundreds of kilometres from the eruption.", "火山灰从喷发处飘出数百公里。"],
"motion": ["Newton explained the laws of motion in the seventeenth century.", "牛顿在十七世纪解释了运动定律。"],
"chunk": ["A large chunk of rock broke off the asteroid.", "一大块岩石从小行星上脱落。"],
"vent": ["Gases escape through vents in the ocean floor.", "气体从海底的喷口逸出。"],
"spacecraft": ["The spacecraft took eight months to reach the planet.", "这艘航天器花了八个月到达该行星。"],
"tail": ["A comet's tail becomes visible when it nears the sun.", "彗星接近太阳时尾巴会变得可见。"],
"spaceship": ["In the film, the spaceship travels faster than light.", "影片中飞船的飞行速度超过光速。"],
"curve": ["The path of the planet forms a slight curve.", "该行星的轨迹形成一条微小的弧线。"],
"probe": ["A probe was sent to examine the surface more closely.", "探测器被派去更仔细地考察表面。"],
"module": ["The crew moved from the command module into the lander.", "乘组从指令舱转移到着陆器。"],
"propulsion": ["The new propulsion system uses far less fuel.", "新的推进系统耗油少得多。"],
"pressure": ["The pressure inside the tank must be kept steady.", "罐内的压力必须保持稳定。"],
"flyby": ["The flyby gave scientists their first close look at the moon.", "这次飞掠让科学家首次近距离观察该卫星。"],
"dynamics": ["He studies the dynamics of gas clouds in space.", "他研究太空中气体云的动力学。"],
"observatory": ["The observatory sits at the top of a quiet mountain.", "天文台坐落在一座安静的山顶。"],
"telescope": ["You can see the rings of Saturn through a small telescope.", "用小型望远镜就能看到土星环。"],
"spectacle": ["The night sky over the desert was a remarkable spectacle.", "沙漠上空的夜空景象极为壮观。"],
"substance": ["The sample contained an unknown substance.", "样本中含有一种未知物质。"],
"composition": ["Scientists analysed the composition of the rock.", "科学家分析了这块岩石的成分。"],
"fossil": ["The fossil shows the shape of a creature that lived long ago.", "这块化石显示出很久以前生物的形状。"],
"orbit": ["The satellite completes one orbit every ninety minutes.", "这颗卫星每九十分钟绕行一圈。"],
"ecliptic": ["The planets move along the ecliptic across our sky.", "行星沿着黄道穿过我们的天空。"],
"diameter": ["The diameter of that crater is nearly two kilometres.", "那个环形山的直径接近两公里。"],
"radius": ["They measured the radius of the planet's orbit.", "他们测量了该行星轨道的半径。"],
"sample": ["The rover collected a sample of surface dust.", "巡视器采集了一份表面尘埃样本。"],
"specimen": ["Each specimen was labelled and stored carefully.", "每份标本都被仔细标记并保存。"],
"particle": ["A tiny particle of dust can damage a spacecraft window.", "微小的尘粒也可能损坏航天器的舷窗。"],
"synthesise": ["Plants synthesise sugar using energy from sunlight.", "植物利用阳光的能量合成糖。"],
"molecule": ["A water molecule contains two hydrogen atoms and one oxygen atom.", "一个水分子包含两个氢原子和一个氧原子。"],
"atom": ["Atoms are far too small to see with a normal microscope.", "原子太小，用普通显微镜看不到。"],
"formation": ["The formation of stars takes millions of years.", "恒星的形成需要数百万年。"],
"method": ["They developed a new method for measuring distance in space.", "他们开发了一种测量太空距离的新方法。"],
"ion": ["An ion is an atom that has lost or gained electrons.", "离子是失去或获得电子的原子。"],
"spectrum": ["The spectrum of a star tells us what it is made of.", "恒星的光谱能告诉我们它的成分。"],
"electron": ["Electrons orbit the nucleus of an atom.", "电子围绕原子核运动。"],
"dimension": ["The scale of the universe is hard to grasp in three dimensions.", "宇宙的尺度很难用三维空间来理解。"],
"liquid": ["Water is the only common liquid on the planet's surface.", "水是该行星表面唯一常见的液体。"],
"frequency": ["The frequency of the signal changed as the probe moved.", "探测器移动时信号频率发生了变化。"],
"fluid": ["The fluid inside the tank behaves differently in zero gravity.", "罐内流体在失重状态下表现不同。"],
"signal": ["The signal took twenty minutes to reach the Earth.", "这个信号花了二十分钟才传到地球。"],
"solid": ["At that temperature, the gas becomes a solid.", "在那个温度下，气体变成了固体。"],
"circuit": ["A short circuit caused the instrument to fail.", "短路导致仪器故障。"],
"refraction": ["Refraction in the atmosphere makes stars appear to twinkle.", "大气中的折射使星星看起来在闪烁。"],
"ultraviolet": ["Ultraviolet light from the sun can damage your eyes.", "来自太阳的紫外线会伤害眼睛。"],
"discernible": ["No discernible change was found in the readings.", "读数中没有发现可辨识的变化。"],
"invisible": ["Most of the matter in the universe is invisible to us.", "宇宙中大部分物质对我们是不可见的。"],
"collision": ["The collision produced a huge cloud of dust.", "这次碰撞产生了巨大的尘埃云。"],
"squash": ["The impact can squash the metal frame flat.", "撞击能把金属框架压扁。"],
"distinct": ["The two rings around the planet are clearly distinct.", "该行星周围的两道环界限分明。"],
"cataclysmic": ["The star ended its life in a cataclysmic explosion.", "这颗恒星在一场剧变式的爆炸中结束了生命。"],
"despair": ["The crew refused to give in to despair.", "机组人员拒绝陷入绝望。"],
"desperate": ["They made a desperate attempt to repair the antenna.", "他们拼命尝试修复天线。"],
"hopeless": ["The situation looked hopeless, yet they kept working.", "情况看起来毫无希望，但他们仍继续工作。"]
};
