module.exports = {
"education": ["A good education gives you choices later in life.", "良好的教育会在日后给你更多选择。"],
"primary": ["She teaches at a primary school near the town centre.", "她在市中心附近的一所小学教书。"],
"secondary": ["Most students move to secondary school at the age of twelve.", "大多数学生十二岁升入中学。"],
"university": ["He applied to three universities and was accepted by two.", "他申请了三所大学，被其中两所录取。"],
"college": ["She studied design at a college in the north.", "她在北方的一所学院学习设计。"],
"institute": ["The institute runs short courses for working adults.", "这个学院为在职成人开设短期课程。"],
"academy": ["He trained at a military academy for four years.", "他在一所军事学院训练了四年。"],
"learn": ["Children learn languages faster than adults do.", "孩子学语言比成人快。"],
"study": ["She studies chemistry for three hours every evening.", "她每天晚上学三小时化学。"],
"acquire": ["You acquire most of your vocabulary by reading.", "你的大部分词汇是通过阅读获得的。"],
"knowledge": ["His knowledge of local history is remarkable.", "他对本地历史的了解令人称奇。"],
"expertise": ["The project needs expertise in both design and engineering.", "这个项目需要设计和工程两方面的专业知识。"],
"novice": ["The course is designed for complete novices.", "这门课是为完全的初学者设计的。"],
"issue": ["The main issue is how to pay for the repairs.", "主要问题是如何支付维修费用。"],
"affair": ["The whole affair was handled badly from the start.", "整件事从一开始就处理得很糟。"],
"controversial": ["His decision was controversial but ultimately correct.", "他的决定有争议，但最终证明是对的。"],
"recruit": ["The company plans to recruit fifty graduates this year.", "公司计划今年招聘五十名毕业生。"],
"literate": ["Nearly everyone in the country is literate.", "这个国家几乎人人识字。"],
"illiteracy": ["The government launched a campaign against illiteracy.", "政府发起了一场扫盲运动。"],
"problem": ["We spent the morning trying to solve the problem.", "我们花了一上午试图解决这个问题。"],
"puzzle": ["The results were a puzzle to everyone in the team.", "这些结果让团队里的每个人都感到困惑。"],
"riddle": ["The children took turns solving the riddle.", "孩子们轮流猜这个谜语。"],
"obscure": ["The meaning of the sentence is rather obscure.", "这句话的意思相当晦涩。"],
"instil": ["Good teachers instil a love of learning in their students.", "好老师会把热爱学习的精神灌输给学生。"],
"cram": ["He tried to cram everything into the night before the exam.", "他试图在考试前一晚把所有内容都塞进脑子。"],
"emphasise": ["The lecturer emphasised the importance of primary sources.", "讲师强调了第一手资料的重要性。"],
"enhance": ["Regular reading will enhance your writing skills.", "经常阅读会提升你的写作能力。"],
"enable": ["The scholarship enabled her to study abroad.", "这笔奖学金使她得以前往国外学习。"],
"inspire": ["Her teacher inspired her to become a physicist.", "她的老师激励她成为一名物理学家。"],
"motive": ["What was his motive for helping the school?", "他帮助这所学校的动机是什么？"],
"motivate": ["Praise motivates students far better than criticism.", "表扬对学生的激励远胜于批评。"],
"stimulate": ["Good questions stimulate discussion in class.", "好的问题能激发课堂讨论。"],
"spur": ["The competition spurred him to work much harder.", "这场竞争促使他更加努力。"],
"impetus": ["The new funding gave the research fresh impetus.", "新的经费为这项研究注入了新动力。"],
"indulge": ["He indulges his children far too often.", "他太常纵容孩子了。"],
"spoil": ["Grandparents often spoil their grandchildren.", "祖父母常常溺爱孙辈。"],
"intelligent": ["She is one of the most intelligent students in the year.", "她是这个年级最聪明的学生之一。"],
"elite": ["The scholarship is open to a small elite of top students.", "这项奖学金只面向少数顶尖学生。"],
"idiot": ["He felt like an idiot for asking such an obvious question.", "他问了个这么明显的问题，觉得自己像个傻瓜。"],
"clever": ["That was a clever way to solve the puzzle.", "那是解决这个难题的巧妙方法。"],
"smart": ["She was smart enough to check the figures twice.", "她很聪明，把数字核对了两遍。"],
"all-round": ["He is an all-round student who excels in sport and music.", "他是个全面发展的学生，运动和音乐都很出色。"],
"genius": ["The theory was the work of a mathematical genius.", "这个理论是一位数学天才的成果。"],
"wisdom": ["Experience often brings more wisdom than books do.", "经验往往比书本带来更多智慧。"],
"wit": ["Her sharp wit made her popular with classmates.", "她机智过人，很受同学欢迎。"],
"aptitude": ["He showed an early aptitude for mathematics.", "他很早就显露出数学天赋。"],
"capable": ["She is perfectly capable of handling the project alone.", "她完全有能力独自处理这个项目。"],
"excellent": ["His essay was excellent in both structure and style.", "他的文章在结构和文风上都很出色。"],
"outstanding": ["She received an award for outstanding academic performance.", "她因学业成绩优异而获奖。"],
"brilliant": ["He came up with a brilliant solution to the problem.", "他想出了解决这个问题的绝妙办法。"],
"prestige": ["The university gained prestige through its research.", "这所大学凭借研究获得了声望。"],
"reputation": ["The school has a reputation for strict discipline.", "这所学校以纪律严格著称。"],
"eminent": ["An eminent historian gave the opening lecture.", "一位著名历史学家做了开场讲座。"],
"notorious": ["The exam was notorious for being extremely difficult.", "这门考试因极其难考而声名在外。"],
"respect": ["Students here are taught to respect each other's views.", "这里的学生被教导要尊重彼此的观点。"],
"diligent": ["She was a diligent student who never missed a class.", "她是个勤奋的学生，从不缺课。"],
"painstaking": ["The research involved painstaking work over five years.", "这项研究包含了五年细致艰苦的工作。"],
"skill": ["Learning to write well is a skill that takes years.", "学会写好文章是一项需要多年磨练的技能。"],
"approach": ["Her approach to teaching is very practical.", "她的教学方法非常实用。"],
"scheme": ["The school introduced a scheme to reward good attendance.", "学校推出了一项奖励出勤的计划。"],
"scholar": ["He is a respected scholar of ancient languages.", "他是一位受人尊敬的古代语言学者。"],
"scientist": ["The scientist published her findings last month.", "这位科学家上个月发表了研究结果。"],
"headmaster": ["The headmaster addressed the whole school on Monday.", "校长在周一给全校讲话。"],
"principal": ["The principal announced the new timetable.", "校长公布了新的课程表。"],
"dean": ["The dean approved the change to the course.", "院长批准了这门课程的调整。"],
"faculty": ["The faculty voted to revise the curriculum.", "全体教师投票决定修订课程。"],
"professor": ["The professor is known for his clear explanations.", "这位教授以讲解清晰著称。"],
"mentor": ["A good mentor can change the direction of your career.", "一位好的导师能改变你职业的方向。"],
"tutor": ["She hired a tutor to help with mathematics.", "她请了一位家教辅导数学。"],
"lecturer": ["The lecturer handed out notes before starting.", "讲师在开始前分发了讲义。"],
"assistant": ["The research assistant collected all the data.", "研究助理收集了全部数据。"],
"candidate": ["There were over two hundred candidates for the course.", "这门课程有两百多名申请者。"],
"degree": ["She earned her degree in three years.", "她用三年时间取得了学位。"],
"qualify": ["You must pass the final exam to qualify.", "你必须通过期末考试才能取得资格。"],
"certify": ["The board will certify the results next week.", "委员会下周将对结果进行认证。"],
"license": ["He needs a license before he can teach here.", "他在这里教书需要先取得执照。"],
"diploma": ["She received her diploma at the graduation ceremony.", "她在毕业典礼上领取了毕业证书。"],
"diplomat": ["The diplomat spent years working abroad.", "这位外交官在国外工作了多年。"],
"ambassador": ["The ambassador met the students during her visit.", "大使在访问期间会见了学生。"],
"pupil": ["There are thirty pupils in each class.", "每个班有三十名学生。"],
"ceremony": ["The graduation ceremony lasted nearly two hours.", "毕业典礼持续了将近两个小时。"],
"bachelor": ["He completed a bachelor's degree in economics.", "他完成了经济学学士学位。"],
"master": ["She is studying for a master's in education.", "她正在攻读教育学硕士学位。"],
"doctor": ["He was awarded a doctor's degree for his research.", "他因研究被授予博士学位。"],
"fresher": ["Freshers are given a week to settle in.", "新生有一周时间适应环境。"],
"sophomore": ["In her sophomore year she joined the debating society.", "大二那年她加入了辩论社。"],
"junior": ["The junior students help organise the school fair.", "低年级学生帮忙组织学校游园会。"],
"senior": ["Senior students often mentor those in lower years.", "高年级学生常常指导低年级学生。"],
"alumni": ["The university invites alumni back every spring.", "这所大学每年春天都邀请校友返校。"],
"campus": ["The campus is quiet during the summer holidays.", "暑假期间校园很安静。"],
"orientation": ["Orientation week helps new students find their way around.", "迎新周帮助新生熟悉环境。"],
"platform": ["The course uses an online platform for assignments.", "这门课使用在线平台提交作业。"],
"register": ["Students must register for their courses by Friday.", "学生必须在周五前完成选课注册。"],
"roster": ["Her name was not on the class roster.", "她的名字不在班级名册上。"],
"enrol": ["Over four hundred students enrolled in the programme.", "四百多名学生报读了这个项目。"],
"matriculation": ["Matriculation marks the formal start of university life.", "入学注册标志着大学生活的正式开始。"],
"accommodation": ["The university provides accommodation for first-year students.", "学校为一年级学生提供住宿。"],
"dorm": ["He shares a dorm with three other students.", "他和另外三名学生合住一间宿舍。"],
"dining hall": ["The dining hall is busiest between twelve and one.", "食堂在十二点到一点之间最挤。"],
"canteen": ["We usually have lunch in the canteen.", "我们通常在食堂吃午饭。"],
"laboratory": ["All experiments must be done in the laboratory.", "所有实验都必须在实验室完成。"],
"experiment": ["The experiment produced unexpected results.", "这个实验产生了意想不到的结果。"],
"data": ["She spent a week analysing the data.", "她花了一周分析这些数据。"],
"quantity": ["We need a large quantity of paper for the project.", "这个项目需要大量纸张。"],
"quality": ["The quality of the writing improved noticeably.", "文章的质量明显提高了。"],
"library": ["The library stays open until midnight during exams.", "考试期间图书馆开到午夜。"],
"literature": ["The course covers English literature from 1800 onwards.", "这门课涵盖 1800 年以来的英国文学。"],
"article": ["He published an article on climate policy.", "他发表了一篇关于气候政策的文章。"],
"author": ["The author signed copies of her new book.", "作者为她的新书签名。"],
"tale": ["The story is an old tale told in many countries.", "这个故事在许多国家流传已久。"],
"fiction": ["She prefers reading fiction to history.", "比起历史，她更喜欢读小说。"],
"story": ["He told the children a story before bedtime.", "睡前他给孩子们讲了个故事。"],
"diary": ["She kept a diary throughout her first year.", "她第一年一直坚持写日记。"],
"poetry": ["He began writing poetry while at university.", "他上大学时开始写诗。"],
"magazine": ["The magazine publishes a new issue every month.", "这本杂志每月出一期。"],
"journal": ["Her paper appeared in a respected academic journal.", "她的论文发表在一份权威学术期刊上。"],
"coverage": ["The report gave wide coverage to the new policy.", "这份报告对新政策做了广泛报道。"],
"bibliography": ["Always include a bibliography at the end of your essay.", "论文末尾一定要附参考文献。"],
"encyclopedia": ["He looked the term up in an encyclopedia.", "他在百科全书中查阅了这个术语。"],
"biography": ["She is writing a biography of a nineteenth-century scientist.", "她正在写一位十九世纪科学家的传记。"],
"documentary": ["We watched a documentary about deep-sea life.", "我们看了一部关于深海生物的纪录片。"],
"profile": ["The article included a short profile of the author.", "文章附有一份简短的作者简介。"],
"draft": ["Write a first draft and then revise it.", "先写初稿，然后再修改。"],
"brochure": ["The college sent a brochure about its courses.", "学院寄来了一本介绍课程的册子。"],
"manual": ["Read the manual before using the machine.", "使用机器前先读说明书。"],
"frame": ["The picture was hung in a plain wooden frame.", "这幅画装在一个素木画框里。"],
"index": ["Look the topic up in the index at the back.", "在书后的索引里查这个主题。"],
"catalogue": ["The library catalogue is now available online.", "图书馆目录现在可以在线查询。"],
"category": ["Please put each book in the right category.", "请把每本书归入正确的类别。"],
"inventory": ["The librarian checked the inventory at the end of term.", "学期末图书管理员清点了藏书。"],
"context": ["Try to understand the word from its context.", "试着从语境中理解这个词。"],
"list": ["She made a list of everything she needed to read.", "她把要读的东西都列成了清单。"],
"chapter": ["I read the first three chapters last night.", "昨晚我读了前三章。"],
"series": ["The university runs a series of public lectures.", "这所大学举办一系列公开讲座。"],
"volume": ["The encyclopedia runs to twenty volumes.", "这套百科全书有二十卷。"],
"reel": ["The old film was stored on a single reel.", "这部老影片存在一个胶片盘上。"],
"major": ["Economics was her major at university.", "她在大学的主修是经济学。"],
"minor": ["He took a minor in philosophy alongside his main subject.", "他在主修之外辅修了哲学。"],
"sociology": ["She chose sociology because she wanted to study society.", "她选社会学是因为想研究社会。"],
"politics": ["He studied politics and history at university.", "他在大学学的是政治学和历史。"],
"economics": ["Economics helps explain why prices change.", "经济学有助于解释价格为何变化。"],
"marketing": ["She works in marketing for a small company.", "她在一家小公司做市场营销。"],
"accounting": ["Accounting requires both accuracy and patience.", "会计既需要准确，也需要耐心。"],
"audit": ["The annual audit took two weeks to complete.", "年度审计花了两周完成。"],
"statistics": ["The statistics show a steady rise in attendance.", "统计数据显示出勤率稳步上升。"],
"psychology": ["He is reading psychology at university.", "他在大学攻读心理学。"],
"philosophy": ["Her philosophy course covers ancient and modern thinkers.", "她的哲学课涵盖古代和现代思想家。"],
"logic": ["The argument is sound in both form and logic.", "这个论证在形式和逻辑上都成立。"],
"biology": ["Biology was his favourite subject at school.", "生物学是他上学时最喜欢的科目。"],
"physics": ["Physics explains how forces affect motion.", "物理学解释力如何影响运动。"],
"chemistry": ["She won a prize for her chemistry project.", "她的化学项目获了奖。"],
"agriculture": ["He studied agriculture before returning to the family farm.", "他学完农业后回到了自家的农场。"],
"logistics": ["The course covers logistics and supply chain management.", "这门课涵盖物流与供应链管理。"],
"history": ["History teaches us how past decisions shape the present.", "历史教我们过去的决定如何塑造现在。"],
"geography": ["In geography we learned about rivers and coastlines.", "地理课上我们学习了河流和海岸线。"],
"engineering": ["She chose engineering because she enjoyed solving practical problems.", "她选工程学是因为喜欢解决实际问题。"],
"mechanics": ["The mechanics of the engine are surprisingly simple.", "这台发动机的机械原理出奇地简单。"],
"electronics": ["He repairs electronics in a small workshop.", "他在一个小作坊里修电子产品。"],
"calculus": ["Calculus is required for most science degrees.", "大多数理科专业都要求学微积分。"],
"geometry": ["Geometry deals with shapes, sizes and angles.", "几何学研究形状、大小和角度。"],
"algebra": ["Algebra uses letters to represent unknown numbers.", "代数用字母表示未知数。"],
"plus": ["Two plus three equals five.", "二加三等于五。"],
"sum": ["The sum of these numbers is too large to check quickly.", "这些数的总和太大，无法快速核对。"],
"total": ["The total cost came to just under a thousand pounds.", "总费用略低于一千英镑。"],
"merger": ["The merger of the two departments saved money.", "两个部门的合并节省了开支。"],
"equation": ["He solved the equation in less than a minute.", "他不到一分钟就解出了这个方程。"],
"identical": ["The two results were almost identical.", "这两个结果几乎完全相同。"],
"minus": ["Ten minus four leaves six.", "十减四得六。"],
"subtract": ["Subtract the smaller number from the larger one.", "用大数减去小数。"],
"divide": ["Divide the total by the number of students.", "用总数除以学生人数。"],
"dividend": ["In this sum, twenty is the dividend.", "在这道题里，二十是被除数。"],
"remainder": ["Nine divided by two leaves a remainder of one.", "九除以二余一。"],
"rational": ["A rational number can be written as a fraction.", "有理数可以写成分数形式。"],
"parameter": ["The experiment was repeated with different parameters.", "这个实验用不同参数重复进行。"],
"variable": ["In this equation, x is the variable.", "在这个方程中，x 是变量。"],
"even": ["Two, four and six are even numbers.", "二、四、六是偶数。"],
"odd": ["One, three and five are odd numbers.", "一、三、五是奇数。"],
"mean": ["The mean of these five numbers is twelve.", "这五个数的平均值是十二。"],
"double": ["The population of the town has doubled in twenty years.", "这个镇的人口二十年间翻了一番。"],
"triple": ["Their income tripled after the new contract.", "新合同签订后他们的收入增长了两倍。"],
"multiple": ["Twelve is a multiple of both three and four.", "十二既是三的倍数，也是四的倍数。"]
};
