module.exports = {
"maximum": ["The maximum number of students in a class is twenty-five.", "一个班最多二十五名学生。"],
"minimum": ["You need a minimum of three years' experience.", "你至少需要三年的经验。"],
"approximately": ["The journey takes approximately two hours by train.", "坐火车这段路程大约需要两小时。"],
"chart": ["The chart shows how the figures changed over time.", "这张图表显示了数字随时间的变化。"],
"graph": ["She plotted the results on a simple graph.", "她把结果画在了一张简单的图表上。"],
"diagram": ["The diagram makes the process much easier to follow.", "这张示意图让整个过程容易理解多了。"],
"table": ["The data are presented in the table below.", "数据列在下面的表格中。"],
"matrix": ["The results were arranged in a matrix.", "结果被排列成一个矩阵。"],
"rectangle": ["The room is a narrow rectangle with one window.", "这个房间是个狭长的长方形，只有一扇窗。"],
"angle": ["Measure the angle between the two lines.", "测量这两条线之间的角度。"],
"triangle": ["A triangle has three sides and three angles.", "三角形有三条边和三个角。"],
"diagonal": ["Draw a diagonal line from one corner to the other.", "从一个角到对角画一条对角线。"],
"straight": ["Draw a straight line between the two points.", "在这两点之间画一条直线。"],
"circle": ["The children sat in a circle on the floor.", "孩子们围坐在地上成一个圈。"],
"round": ["The table has a round top and three legs.", "这张桌子桌面是圆的，有三条腿。"],
"dot": ["Mark each correct answer with a dot.", "用圆点标出每个正确答案。"],
"sphere": ["The Earth is not a perfect sphere.", "地球并非完美的球体。"],
"cone": ["Ice cream was served in a paper cone.", "冰淇淋装在纸筒里端上来。"],
"extent": ["To some extent, the problem was our own fault.", "在某种程度上，这个问题是我们自己的错。"],
"width": ["The width of the river is about forty metres.", "这条河宽约四十米。"],
"length": ["Cut the wood to the right length.", "把木头切成合适的长度。"],
"decimal": ["Write your answer as a decimal to two places.", "把答案写成保留两位小数的形式。"],
"per cent": ["Nearly ninety per cent of students passed the exam.", "近百分之九十的学生通过了考试。"],
"proportion": ["A large proportion of the class chose the same topic.", "班里很大一部分人选了同一个题目。"],
"rate": ["The unemployment rate fell slightly last month.", "上个月失业率略有下降。"],
"ratio": ["The ratio of teachers to students is one to fifteen.", "师生比是一比十五。"],
"fraction": ["Only a small fraction of applicants were accepted.", "只有一小部分申请者被录取。"],
"scale": ["The map is drawn to a scale of one to fifty thousand.", "这张地图按一比五万的比例绘制。"],
"ounce": ["Add two ounces of butter to the mixture.", "在混合物中加入两盎司黄油。"],
"density": ["The density of the liquid increases as it cools.", "液体冷却时密度会增大。"],
"mercury": ["The thermometer uses mercury to measure temperature.", "温度计用水银来测量温度。"],
"battery": ["The battery needs charging every two days.", "这块电池每两天需要充一次电。"],
"volt": ["This device runs on twelve volts.", "这个装置使用十二伏电压。"],
"radiate": ["The heater radiates warmth across the room.", "加热器向整个房间散发热量。"],
"emit": ["The lamp emits a soft yellow light.", "这盏灯发出柔和的黄光。"],
"transparent": ["The container is transparent so you can see the level.", "这个容器是透明的，能看见液面高度。"],
"hollow": ["The tree trunk was completely hollow.", "这棵树干完全是空心的。"],
"ozone": ["The ozone layer protects us from harmful radiation.", "臭氧层保护我们免受有害辐射。"],
"gravity": ["Gravity keeps the planets in their orbits.", "引力使行星保持在轨道上。"],
"friction": ["There is always some friction between moving surfaces.", "运动的表面之间总会有一些摩擦。"],
"eccentric": ["The old professor was famous for his eccentric habits.", "这位老教授以古怪的习惯闻名。"],
"displace": ["The new system will displace the old one entirely.", "新系统将完全取代旧系统。"],
"boil": ["Boil the water before adding the rice.", "加米之前先把水烧开。"],
"melt": ["The ice will melt quickly in this heat.", "在这种高温下冰会很快融化。"],
"dissolve": ["Stir until the sugar dissolves completely.", "搅拌直到糖完全溶解。"],
"rust": ["The gate had begun to rust at the hinges.", "大门在铰链处已经开始生锈。"],
"dilute": ["Dilute the solution with an equal amount of water.", "用等量的水稀释这个溶液。"],
"inherent": ["There are inherent risks in any experiment.", "任何实验都有内在的风险。"],
"acid": ["This acid is too strong to use without gloves.", "这种酸太强，不戴手套不能用。"],
"noxious": ["The factory released noxious gas into the air.", "工厂向空气中排放了有毒气体。"],
"static": ["The charge stays static until it is discharged.", "电荷在放电之前保持静止。"],
"inert": ["These gases are chemically inert.", "这些气体在化学上是惰性的。"],
"formula": ["The formula for calculating the area is simple.", "计算面积的公式很简单。"],
"component": ["Each component of the machine can be replaced separately.", "机器的每个部件都可以单独更换。"],
"compose": ["The committee is composed of twelve members.", "委员会由十二名成员组成。"],
"mixture": ["The mixture should be stirred for two minutes.", "这个混合物应搅拌两分钟。"],
"blend": ["This tea is a blend of three different leaves.", "这款茶由三种不同的茶叶混合而成。"],
"theory": ["The theory was later tested by many experiments.", "这个理论后来被许多实验所检验。"],
"empirical": ["The claim is not supported by empirical evidence.", "这一说法没有实证证据支持。"],
"practical": ["The course includes both theory and practical work.", "这门课既包括理论也包括实践。"],
"doctrine": ["The doctrine was accepted for centuries.", "这一学说被接受了几个世纪。"],
"principle": ["The machine works on a very simple principle.", "这台机器的工作原理非常简单。"],
"discipline": ["Chemistry is a demanding discipline.", "化学是一门要求严格的学科。"],
"timetable": ["The new timetable starts next Monday.", "新的课程表从下周一开始执行。"],
"schedule": ["We are slightly behind schedule on this project.", "这个项目我们略微落后于计划。"],
"deadline": ["The deadline for the essay is Friday at noon.", "论文的截止时间是周五中午。"],
"term": ["The autumn term begins in early September.", "秋季学期九月初开始。"],
"semester": ["She spent a semester studying in Berlin.", "她在柏林学习了一个学期。"],
"course": ["He signed up for a course in statistics.", "他报了一门统计学课程。"],
"lesson": ["Today's lesson focused on essay structure.", "今天的课重点讲文章结构。"],
"curriculum": ["The school has revised its science curriculum.", "学校修订了科学课程。"],
"fundamental": ["Reading is a fundamental skill for academic work.", "阅读是学术工作的基本技能。"],
"seminar": ["Everyone must present once during the seminar.", "研讨课上每个人都必须做一次报告。"],
"forum": ["The website provides a forum for students to ask questions.", "这个网站为学生提问提供了一个论坛。"],
"syllabus": ["The syllabus lists all the topics for the term.", "教学大纲列出了本学期的全部主题。"],
"system": ["The library uses an electronic system for borrowing.", "图书馆使用电子系统借书。"],
"rudimentary": ["He has only a rudimentary knowledge of French.", "他的法语只有初步的水平。"],
"basic": ["Start with the basic rules before moving on.", "先掌握基本规则，再继续深入。"],
"elementary": ["These are elementary mistakes that should be avoided.", "这些都是应当避免的低级错误。"],
"profound": ["Her research had a profound effect on the field.", "她的研究对该领域产生了深远影响。"],
"superficial": ["His understanding of the topic is rather superficial.", "他对这个主题的理解相当肤浅。"],
"surface": ["Do not judge the argument on its surface alone.", "不要仅从表面判断这个论点。"],
"compulsory": ["Physical education is compulsory in most schools.", "体育在大多数学校是必修的。"],
"prerequisite": ["Statistics is a prerequisite for this course.", "统计学是这门课的先修要求。"],
"selective": ["The university is highly selective in its admissions.", "这所大学的录取非常挑剔。"],
"elective": ["She chose two elective courses in her final year.", "她在最后一年选了两门选修课。"],
"assignment": ["The assignment must be handed in by Monday.", "作业必须在周一前提交。"],
"submit": ["You can submit your essay online.", "你可以在线提交论文。"],
"preview": ["Students get a preview of the exam topics.", "学生们可以预先了解考试主题。"],
"revise": ["She revised her notes the night before the test.", "考前一晚她复习了笔记。"],
"inspect": ["The teacher inspected the laboratory before the class.", "上课前老师检查了实验室。"],
"skim": ["Skim the article first, then read it closely.", "先略读文章，再仔细读。"],
"scan": ["He scanned the page looking for a specific name.", "他扫视页面寻找一个特定的名字。"],
"scrutinise": ["The committee will scrutinise every application.", "委员会将仔细审查每一份申请。"],
"recite": ["The children recited the poem from memory.", "孩子们凭记忆背诵了这首诗。"],
"examination": ["The final examination lasts three hours.", "期末考试持续三个小时。"],
"test": ["We have a short test every Friday.", "我们每周五都有一次小测验。"],
"quiz": ["The quiz covered everything from the first month.", "这次小测涵盖了第一个月的全部内容。"],
"presentation": ["Her presentation was clear and well organised.", "她的报告清晰且条理分明。"],
"plagiarise": ["Students who plagiarise will fail the course.", "抄袭的学生将无法通过这门课。"],
"copy": ["Please make a copy of this page for everyone.", "请把这一页给每人复印一份。"],
"print": ["The print is too small to read without glasses.", "字号太小，不戴眼镜看不清。"],
"thesis": ["He is writing his thesis on urban planning.", "他正在写关于城市规划的论文。"],
"paper": ["She published a paper on marine biology.", "她发表了一篇关于海洋生物的论文。"],
"heading": ["Each section has a clear heading.", "每一节都有清晰的标题。"],
"outset": ["From the outset, the project faced difficulties.", "从一开始这个项目就面临困难。"],
"outline": ["Write an outline before you begin the essay.", "开始写文章前先列个提纲。"],
"point": ["I do not see the point of repeating the same exercise.", "我不明白重复同一个练习有什么意义。"],
"gist": ["I only caught the gist of his argument.", "我只听懂了他论点的要点。"],
"opinion": ["In my opinion, the second option is better.", "在我看来，第二个选择更好。"],
"introduce": ["Let me introduce the main topic of today's lecture.", "让我介绍今天讲座的主要话题。"],
"reference": ["The essay should include at least five references.", "这篇论文至少应包含五处引用。"],
"cite": ["He cited three studies to support his claim.", "他引用了三项研究来支持自己的主张。"],
"elicit": ["The question elicited a range of different answers.", "这个问题引出了各种不同的答案。"],
"quote": ["She quoted a line from the original text.", "她引用了原文中的一句话。"],
"summary": ["Write a short summary at the end of each chapter.", "在每章末尾写一段简短的总结。"],
"assume": ["Do not assume that everyone has read the book.", "不要假设每个人都读过这本书。"],
"presume": ["I presume you have already registered for the course.", "我猜你已经注册了这门课。"],
"suppose": ["Suppose the experiment fails — what then?", "假如实验失败，那该怎么办？"],
"hypothesis": ["The data did not support the original hypothesis.", "数据并不支持最初的假设。"],
"speculate": ["It is too early to speculate about the results.", "现在推测结果还为时过早。"],
"predict": ["It is difficult to predict how the market will move.", "很难预测市场会如何变化。"],
"perceive": ["Children perceive the world differently from adults.", "孩子感知世界的方式与成人不同。"],
"detect": ["The instrument can detect very small changes.", "这台仪器能检测到非常细微的变化。"],
"discern": ["It was hard to discern any pattern in the numbers.", "很难在这些数字中辨别出什么规律。"],
"recognise": ["I did not recognise him after all these years.", "这么多年过去，我没认出他来。"],
"conscious": ["She was conscious of the fact that time was short.", "她意识到时间不多了。"],
"reckon": ["I reckon the whole thing will take about a week.", "我估计整件事大约要一周。"],
"deem": ["The proposal was deemed unacceptable by the board.", "该提案被董事会认为不可接受。"],
"imply": ["His silence seemed to imply agreement.", "他的沉默似乎暗示着同意。"],
"insist": ["She insisted on checking every figure herself.", "她坚持要亲自核对每一个数字。"],
"persist": ["The problem persists despite several attempts to fix it.", "尽管多次尝试解决，问题依然存在。"],
"understand": ["I understand the theory but not how to apply it.", "我理解这个理论，但不知道如何应用。"],
"comprehend": ["It is hard to comprehend the size of the universe.", "很难理解宇宙的尺度。"],
"analyse": ["We need to analyse the data more carefully.", "我们需要更仔细地分析这些数据。"],
"diagnose": ["The engineer diagnosed the fault within an hour.", "工程师在一小时内诊断出了故障。"],
"infer": ["We can infer from the results that the method works.", "从结果可以推断出这个方法是可行的。"],
"deduce": ["From these clues he deduced the answer.", "他从这些线索中推断出了答案。"],
"conclude": ["The study concludes that more research is needed.", "这项研究得出结论：还需要更多研究。"],
"analogy": ["He drew an analogy between the brain and a computer.", "他把大脑与计算机作了类比。"],
"compare": ["Compare the two texts and note the differences.", "比较这两篇文章并记下差异。"],
"contradiction": ["There is an obvious contradiction in his argument.", "他的论证中存在明显的矛盾。"],
"disagree": ["Experts still disagree about the cause.", "专家对原因仍有分歧。"],
"differ": ["Opinions differ widely on this question.", "在这个问题上意见分歧很大。"],
"diverse": ["The class comes from very diverse backgrounds.", "这个班的同学背景非常多元。"],
"nuance": ["The translation misses some of the nuance.", "这个译文漏掉了一些细微差别。"],
"inductive": ["Inductive reasoning moves from examples to a general rule.", "归纳推理从例子出发得出一般规律。"],
"thorough": ["She made a thorough study of the records.", "她对这些记录作了彻底研究。"],
"example": ["Give an example to support your point.", "举个例子来支持你的观点。"],
"instance": ["In this instance, the rule does not apply.", "在这个情况下，该规则不适用。"],
"confirm": ["Further tests confirmed the original finding.", "进一步的测试证实了最初的发现。"],
"demonstrate": ["The experiment demonstrates the principle clearly.", "这个实验清楚地演示了该原理。"],
"illustrate": ["The diagram illustrates how the process works.", "这张图说明了这个过程是如何运作的。"],
"manifest": ["The symptoms may not manifest for several days.", "症状可能几天后才会显现。"],
"prove": ["It is impossible to prove a negative.", "要证明一个否定命题是不可能的。"],
"decide": ["We decided to postpone the meeting until next week.", "我们决定把会议推迟到下周。"],
"observe": ["Researchers observed the birds for six months.", "研究人员观察了这些鸟六个月。"],
"inquire": ["She inquired about the entry requirements.", "她询问了入学要求。"],
"query": ["Please send any queries to the course office.", "如有疑问请发邮件至课程办公室。"],
"questionnaire": ["Two hundred people completed the questionnaire.", "两百人填写了问卷。"],
"achieve": ["She achieved the highest mark in the year.", "她取得了全年级最高分。"],
"determine": ["The test will determine which level suits you.", "这项测试将确定哪个级别适合你。"],
"accomplish": ["They accomplished the task in half the expected time.", "他们用预期时间的一半完成了任务。"],
"attain": ["He attained a first-class degree.", "他取得了一等学位。"],
"credit": ["You will receive credit for both courses.", "两门课程你都能获得学分。"],
"grade": ["She was pleased with her grade in mathematics.", "她对自己的数学成绩很满意。"],
"rank": ["The university ranks among the top ten nationally.", "这所大学在全国排名前十。"],
"queue": ["A long queue formed outside the examination hall.", "考场外排起了长队。"],
"score": ["He scored well above the class average.", "他的得分远高于班级平均分。"],
"mark": ["The teacher marked the papers over the weekend.", "老师周末批改了试卷。"],
"grant": ["The university granted her a year's leave.", "学校批准了她一年的休假。"],
"praise": ["The tutor praised her clear and logical writing.", "导师称赞她写得清晰而有逻辑。"],
"appreciate": ["I really appreciate the help you gave me.", "我非常感谢你给我的帮助。"],
"feedback": ["Students receive written feedback on every essay.", "每篇作文学生都会收到书面反馈。"],
"overestimate": ["People often overestimate how much they can do in a day.", "人们常常高估自己一天能完成的事。"],
"fellowship": ["She was awarded a research fellowship for two years.", "她获得了两年的研究奖学金。"],
"scholarship": ["He won a scholarship to study overseas.", "他获得了出国留学的奖学金。"],
"reward": ["There is a reward for the best student project.", "最佳学生项目设有奖励。"],
"award": ["She received an award for academic excellence.", "她因学业优异而获奖。"],
"prize": ["The prize is given to the top three students.", "该奖项颁给前三名学生。"],
"fee": ["Tuition fees have risen again this year.", "今年学费又上涨了。"]
};
